# Generated by Django 3.2.3 on 2024-04-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInformation',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_sourcetodestination', models.CharField(max_length=80)),
                ('bus_viaroad', models.TextField()),
                ('bus_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('routes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('way_points', models.TextField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.businformation')),
            ],
        ),
        migrations.AddField(
            model_name='businformation',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.route'),
        ),
    ]
